'use strict';

// Admin UI routes for the server-rendered API reference.
//
// This is the eventual replacement for /admin/swagger, which ships the OpenAPI document
// to the browser and lets swagger-ui build the DOM. Here the whole page is HTML by the
// time it leaves the worker - see lib/api-reference/ for the model.
//
// This is the "API Reference" entry in the side menu. /admin/swagger still serves the
// swagger-ui page but is no longer linked, pending its removal.

const Joi = require('joi');
const Boom = require('@hapi/boom');

const { failAction } = require('../tools');
const tokens = require('../tokens');
const { getIndexView, getTagView, getNavView } = require('../api-reference');

// Lifetime of the throwaway tokens the reference page mints for its try-it panels. Long
// enough to read through the docs, short enough that a token left in a browser tab is
// not a lasting credential.
const TEMP_TOKEN_TTL = 60 * 60 * 1000;

function init(args) {
    const { server } = args;

    server.route({
        method: 'GET',
        path: '/admin/reference',
        async handler(request, h) {
            const view = await getIndexView(request);

            // secondaryNav opts this page into the layout's second navigation column,
            // rendered flush against the main sidebar (views/layout/app.hbs)
            return h.view('reference/index', Object.assign({ pageTitle: 'API Reference', menuReference: true, secondaryNav: 'reference/nav' }, view), {
                layout: 'app'
            });
        }
    });

    // Access-token page. A literal segment, so hapi routes it ahead of /{tag} below - no
    // tag slug may be `token` or it would be shadowed, which test/api-reference-test.js
    // asserts against RESERVED_SLUGS.
    server.route({
        method: 'GET',
        path: '/admin/reference/token',
        async handler(request, h) {
            const view = await getNavView(request);

            return h.view('reference/token', Object.assign({ pageTitle: 'Access token', menuReference: true, secondaryNav: 'reference/nav' }, view), {
                layout: 'app'
            });
        }
    });

    server.route({
        method: 'GET',
        path: '/admin/reference/{tag}',
        async handler(request, h) {
            const view = await getTagView(request, request.params.tag);

            if (!view) {
                throw Boom.notFound('Unknown endpoint group');
            }

            return h.view('reference/tag', Object.assign({ pageTitle: `${view.tag.name} API`, menuReference: true, secondaryNav: 'reference/nav' }, view), {
                layout: 'app'
            });
        },

        options: {
            validate: {
                options: {
                    stripUnknown: true,
                    abortEarly: false,
                    convert: true
                },
                failAction,
                params: Joi.object({
                    // Slugs are generated by slugify() in lib/api-reference/format.js;
                    // anything else cannot match a tag and is rejected before the lookup
                    tag: Joi.string()
                        .max(64)
                        .pattern(/^[a-z0-9-]+$/)
                        .required()
                })
            }
        }
    });

    // Mints a short-lived, api-scoped token for the try-it panels, so trying an endpoint
    // does not mean creating a permanent credential and remembering to delete it.
    server.route({
        method: 'POST',
        path: '/admin/reference/token',

        async handler(request) {
            try {
                // Same gate as POST /admin/tokens/new, for the same reason: a token is
                // never invalidated once minted, so an unauthenticated caller must not be
                // able to obtain one. `server.auth.default('session')` is applied
                // conditionally and only in the worker that observed the password being
                // set, so this keys on whether THIS request carries an admin session
                // rather than on the global secured-state.
                if (!request.auth.isAuthenticated) {
                    throw Boom.forbidden('Can not provision an access token without an authenticated admin session');
                }

                const expires = Date.now() + TEMP_TOKEN_TTL;

                const token = await tokens.provision({
                    ip: request.app.ip,
                    remoteAddress: request.app.ip,
                    description: 'Temporary token for the API reference',
                    scopes: ['api'],
                    expires
                });

                return { success: true, token, expires };
            } catch (err) {
                request.logger.error({ msg: 'Failed to mint a temporary reference token', err, remoteAddress: request.app.ip });
                if (Boom.isBoom(err)) {
                    return Object.assign({ success: false }, err.output.payload);
                }
                return { success: false, error: err.code || 'Error', message: err.message };
            }
        }
    });
}

module.exports = init;
