'use strict';

// Admin UI routes for the server-rendered API reference.
//
// This replaced the bundled swagger-ui page, which shipped the OpenAPI document to the
// browser and let swagger-ui build the DOM. Here the whole page is HTML by the time it
// leaves the worker - see lib/api-reference/ for the model.
//
// This is the "API Reference" entry in the side menu. /admin/swagger is kept only as a
// redirect for deep links written against the old page.

const Joi = require('joi');
const Boom = require('@hapi/boom');

const { failAction } = require('../tools');
const { jsonErrorPayload, authAwareLevel } = require('./route-helpers');
const tokens = require('../tokens');
const { getIndexView, getTagView, getNavView, getRedirectView } = require('../api-reference');

// Lifetime of the throwaway tokens the reference page mints for its try-it panels. Long
// enough to read through the docs, short enough that a token left in a browser tab is
// not a lasting credential.
const TEMP_TOKEN_TTL = 60 * 60 * 1000;

// Only tokens carrying this description are revocable through the reference page. It is
// what the mint route sets, so a pasted token - which the user owns and may still need -
// can never be deleted by clearing the field.
const TEMP_TOKEN_DESCRIPTION = 'Temporary token for the API reference';

// Opts every reference page into the layout's second navigation column, rendered flush
// against the main sidebar (views/layout/app.hbs). The label names it where the column
// cannot be shown as a column - below lg it collapses to a single row carrying this text.
const SECONDARY_NAV = { secondaryNav: 'reference/nav', secondaryNavLabel: 'Endpoints' };

function init(args) {
    const { server } = args;

    server.route({
        method: 'GET',
        path: '/admin/reference',
        async handler(request, h) {
            const view = await getIndexView(request);

            return h.view('reference/index', Object.assign({ pageTitle: 'API Reference', menuReference: true, ...SECONDARY_NAV }, view), {
                layout: 'app'
            });
        }
    });

    // Access-token page. A literal segment, so hapi routes it ahead of /{tag} below - no
    // tag slug may be `token` or it would be shadowed, which test/api-reference-test.js
    // asserts against RESERVED_SLUGS.
    server.route({
        method: 'GET',
        path: '/admin/reference/token',
        async handler(request, h) {
            const view = await getNavView(request);

            return h.view('reference/token', Object.assign({ pageTitle: 'Access token', menuReference: true, ...SECONDARY_NAV }, view), {
                layout: 'app'
            });
        }
    });

    server.route({
        method: 'GET',
        path: '/admin/reference/{tag}',
        async handler(request, h) {
            const view = await getTagView(request, request.params.tag);

            if (!view) {
                throw Boom.notFound('Unknown endpoint group');
            }

            return h.view('reference/tag', Object.assign({ pageTitle: `${view.tag.name} API`, menuReference: true, ...SECONDARY_NAV }, view), {
                layout: 'app'
            });
        },

        options: {
            validate: {
                options: {
                    stripUnknown: true,
                    abortEarly: false,
                    convert: true
                },
                failAction,
                params: Joi.object({
                    // Slugs are generated by slugify() in lib/api-reference/format.js;
                    // anything else cannot match a tag and is rejected before the lookup
                    tag: Joi.string()
                        .max(64)
                        .pattern(/^[a-z0-9-]+$/)
                        .required()
                })
            }
        }
    });

    // Compatibility shim for the retired swagger-ui page. Old versions of EmailEngine, and
    // any bookmark, link here as /admin/swagger#/Tag/operationId; a fragment never reaches
    // the server, so the page maps it in the browser. Links inside this version point at
    // /admin/reference directly.
    server.route({
        method: 'GET',
        path: '/admin/swagger',
        async handler(request, h) {
            const view = await getRedirectView(request);

            return h.view('reference/redirect', Object.assign({ pageTitle: 'API Reference', menuReference: true }, view), { layout: 'app' });
        }
    });

    // Mints a short-lived, api-scoped token for the try-it panels, so trying an endpoint
    // does not mean creating a permanent credential and remembering to delete it.
    server.route({
        method: 'POST',
        path: '/admin/reference/token',

        async handler(request) {
            try {
                // Same gate as POST /admin/tokens/new, for the same reason: a token is
                // never invalidated once minted, so an unauthenticated caller must not be
                // able to obtain one. `server.auth.default('session')` is applied
                // conditionally and only in the worker that observed the password being
                // set, so this keys on whether THIS request carries an admin session
                // rather than on the global secured-state.
                if (!request.auth.isAuthenticated) {
                    throw Boom.forbidden('Can not provision an access token without an authenticated admin session');
                }

                const expires = Date.now() + TEMP_TOKEN_TTL;

                const token = await tokens.provision({
                    ip: request.app.ip,
                    remoteAddress: request.app.ip,
                    description: TEMP_TOKEN_DESCRIPTION,
                    scopes: ['api'],
                    expires
                });

                return { success: true, token, expires };
            } catch (err) {
                request.logger[authAwareLevel(err)]({ msg: 'Failed to mint a temporary reference token', err, remoteAddress: request.app.ip });
                return jsonErrorPayload(err);
            }
        }
    });

    // Revokes a token minted above, so clearing it in the UI actually removes it rather
    // than leaving a working credential in Redis until it expires on its own.
    server.route({
        method: 'POST',
        path: '/admin/reference/token/revoke',

        async handler(request) {
            try {
                if (!request.auth.isAuthenticated) {
                    throw Boom.forbidden('Can not revoke an access token without an authenticated admin session');
                }

                // Refuse anything this page did not mint. An admin can delete any token
                // from the Access Tokens page anyway, so this is not a privilege boundary -
                // it stops the reference page from destroying a token the user pasted in.
                let tokenData;
                try {
                    tokenData = await tokens.get(request.payload.token, false, { allowExpired: true });
                } catch (err) {
                    // already gone, or never existed - nothing left to revoke
                    return { success: true, deleted: false };
                }

                if (tokenData.description !== TEMP_TOKEN_DESCRIPTION) {
                    throw Boom.forbidden('Only tokens minted by the API reference can be revoked here');
                }

                await tokens.delete(request.payload.token, { remoteAddress: request.app.ip });

                return { success: true, deleted: true };
            } catch (err) {
                request.logger[authAwareLevel(err)]({ msg: 'Failed to revoke a temporary reference token', err, remoteAddress: request.app.ip });
                return jsonErrorPayload(err);
            }
        },

        options: {
            validate: {
                options: { stripUnknown: true, abortEarly: false, convert: true },
                failAction,
                payload: Joi.object({
                    token: Joi.string().length(64).hex().required().description('The token to revoke')
                })
            }
        }
    });
}

module.exports = init;
