FROM node:18-alpine

ENV EE_DOCKER_LEGACY=true

RUN apk add --no-cache dumb-init

WORKDIR /emailengine
COPY . .

RUN npm install --omit=dev
RUN npm run prepare-docker
RUN chmod +x ./update-info.sh
RUN ./update-info.sh

ENV EENGINE_APPDIR=/emailengine
ENV EENGINE_HOST=0.0.0.0

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD node ${EENGINE_APPDIR}/server.js
